apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-zip
  namespace: 'self-supervised-video'
spec:
  storageClassName: rook-cephfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
