apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
  namespace: 'ece3d-vision'
spec:
  storageClassName: rook-cephfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
