apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-backup
  namespace: 'image-model'
spec:
  storageClassName: rook-cephfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1024Gi
